AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - app/channels/**/*
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - spec/**/*
    - config.ru
    - Guardfile
    - Rakefile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines

Style/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - app/controllers/**/*

Rails:
  Enabled: true
